### ISSUE TITLE
project goal

### ISSUE THREAD

**Issue by DanielRuf** [stokry/wp-sqlite#2]
Isn't this just what https://github.com/aaemnnosttv/wp-sqlite-db is (wp-content/db.php)?

I made a diff with diff -ur and saw no more differences.
Btw, you can automate this also with WP-CLI: https://github.com/DanielRuf-archive/run-local-wordpress/blob/main/run-local-wordpress-v2.sh#L39

**Comment by kkarpieszuk** [comment]
> Btw, you can automate this also with WP-CLI: https://github.com/DanielRuf-archive/run-local-wordpress/blob/main/run-local-wordpress-v2.sh#L39

@DanielRuf the link does not work, you probably shared url of your private repo

**Comment by DanielRuf** [comment]
You are right, yes.

![grafik](https://user-images.githubusercontent.com/827205/168997719-6b1c2f0c-11e0-4336-a90b-42552085dc77.png)

```
# Download sqlite integration plugin in -wp-content folder
curl -verbose -o $(pwd)/wp-content/db.php https://raw.githubusercontent.com/aaemnnosttv/wp-sqlite-db/master/src/db.php
```

**Comment by paulocoghi** [comment]
What are the differences between the two projects?

**Comment by DanielRuf** [comment]
> What are the differences between the two projects?

There is no difference.

This project here has simply added the db.php file from https://github.com/aaemnnosttv/wp-sqlite-db without any further changes to a standard WP setup - you get the same result by following the readme at https://github.com/aaemnnosttv/wp-sqlite-db.

To be clear, I have nothing against this project but it should at least mention the usage of the other project, link to it and its readme so everyone can create this setup themself as there is not much besides "add db.php to WP files and create a repo of it". That would be more helpful for everyone.
