### ISSUE TITLE
Lots of Deprecated PHP warnings on PHP 8.1

### ISSUE THREAD

**Issue by taliesinpenbardd** [stokry/wp-sqlite#6]
Hey, great idea you had there!
However, there are lots of "deprecated" warnings on PHP8.1, it would perhaps be a good thing to adapt your code...
Keep up the good work
[debug.log](https://github.com/stokry/wp-sqlite/files/8708672/debug.log)
.

**Comment by tombrunberg** [comment]
You are aware that WordPress isn't php8.1 compatible yet? The issue is not with this fork.

**Comment by taliesinpenbardd** [comment]
I wasn't, my bad. Issue closed, then. 😃
